- hosts: all
  become: yes
  debugger: on_failed
  gather_facts: no

  tasks:
    - name: Wait until the instance is ready
      ansible.builtin.wait_for_connection:

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: podman present
      ansible.builtin.dnf:
        name: podman
        update_cache: yes
        state: present
