# - name: "Set variables"
#   set_fact:
#     ssh_key_name: "${USER}-poc-aws-key"
#     ssh_private_file_name: "${USER}-poc-aws-key.pem"
#     sg_name: "poc-aws"
#     sg_tag_key: "Name"
#     sg_tag_val: "poc-aws"
#     sg_id: ""
#     ubuntu_x86_id: "ami-0caef02b518350c8b"
#     ec2_type: "t2.micro"
#     ec2_tag_key: "Name"
#     ec2_tag_val: "poc-aws-server"
#     sg_description: "AWS SG for poc-aws"
#     aws_region: "eu-central-1"
#     iam_role_name: "PocRole"
#     policy_name: "PocPolicy"
#     profile_name: "PocProfile"
---
- name: ec2 config
  hosts: localhost
  connection: local
  vars_files:
    - variables.yaml
  tasks:
    - name: create security group
      amazon.aws.ec2_group:
        name: "{{ sg_name }}"
        description: "{{ sg_description }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
